### PR TITLE
Resume manager, part 2

### PR DESCRIPTION
**Pull request by ace-n**
Part 2 of issue #332 (sorting + expiry warnings)

### CODE REVIEW

**Comment by ace-n** [comment]
@sskhandek @achalv Mind signing off on this?

**Comment by sskhandek** [comment]
Also looks good

**Comment by sskhandek** [comment]
@ace-n , can you resolve some merge issues on this front?

**Comment by ace-n** [comment]
This is mergeable, @sskhandek I'm assuming it's good to pull in?

**Comment by sskhandek** [comment]
Yes

**Pull request merged**
