### PR TITLE
Update README.md to force use python2.7

### PR DESCRIPTION
**Pull request by pranaygp**
since we use some outdated modules

### CODE REVIEW

**Comment by sskhandek** [comment]
Did you test this locally to ensure that nothing breaks?

**Comment by sskhandek** [comment]
Also, cc'ding @ace-n @kevinwang

**Comment by pranaygp** [comment]
There are more changes to make but yeah. Don't merge it in yet. I'll update
the README a bit more and let you know.

**Comment by kevinwang** [comment]
+1 This should be harmless.

**Pull request merged**
