### PR TITLE
Implement forcevend script

### PR DESCRIPTION
**Pull request by ace-n**
@milanocookies93 Care to review?

@ajmadsen or Rohan Kapoor may need to set up an SSH key to the Caffeine machine (dep-03?) for this to work.

### CODE REVIEW

**Comment by rohankapoorcom** [comment]
Yeah, this will need an ssh key to allow (web-02?) for siebl-1106-05

**Comment by ace-n** [comment]
Yeah, Liquid runs on web-02.

**Comment by colegleason** [comment]
You can mount the container with access to the host's key. Anyone with
access to deploy docker containers to that host can already access it
anyways, so it shouldn't be a security risk.

**Comment by ace-n** [comment]
Merging this now (to test @rohankapoorcom's SSH key setup); @sskhandek @colegleason let me know if I missed something.

**Comment by colegleason** [comment]
This is incorrect, as it restricts building the docker image to the machine with the key. If you did build and push, it would expose the key. I meant you should mount the file at runtime, not in the build.

https://docs.docker.com/engine/userguide/containers/dockervolumes/

**Comment by colegleason** [comment]
You should just add `-v /root/.ssh:/root/.ssh` to the `docker run` command on the server-specific deploy command. I think there is a file for this on the liquid webserver.

**Comment by ace-n** [comment]
@colegleason OK, thanks for letting me know. I ran into this problem
earlier, but wasn't sure how to fix it.

And yes, there is a "deploy.sh" that we can add this to.

**Pull request merged**
