### PR TITLE
Forcevend hotfix #3

### PR DESCRIPTION
**Pull request by ace-n**

### CODE REVIEW

**Comment by colegleason** [comment]
If these are hotfixes and not being reviewed, you don't have to put all of these through as pull requests.  Quay will build the docker image when master branch is updated. You could also build and test without pushing up here, but I don't know if you have permission to push to the Quay repo or not.

**Comment by ace-n** [comment]
@colegleason Yeah - I thought about pushing directly to master, but I wanted to stick with PR's since I started doing that earlier today.

Admittedly I'm not sure what the best way to handle hotfixes with Github is, so any advice you have on how to build/test hotfixes (other than presumably pushing directly to master) is more than welcome.

**Comment by colegleason** [comment]
I think, that unless prod is completely broken, all code should get a
review. If prod is broken, push directly to master (since it needs to get
fixed ASAP).

These seemed more like development than hotfixes, and probably should be
happening elsewhere entirely. You should probably be building and running a
different container (on a different port). I thought there was a "dev"
config on the webserver somewhere. Once it all looks good, then you would
take you changes and make a formal PR of all of it.

Depending on how you test the container, this may require a separate
branch/tag on the quay.io repo, since you need to pull it from somewhere.
You also might need to be given permission by Adam to push to that repo.

**Comment by ace-n** [comment]
110% agree - a dev environment would be a godsend for work like this. I've
seen scripts for a "dev" setup, but haven't tried building anything
separately - maybe I can throw "Investigate dev Docker instance" up as an
issue?

**Pull request merged**
