### PR TITLE
Use working LDAP auth settings. Fixes #283.

### LINKED ISSUE #283: Authentication changes
As of today, CITES is no longer allowing LDAP/LDAPS binds to Active Directory (for authentication), such as how Liquid is currently running. Thus, we will need to change Liquid's auth to one of the following:

- Shibboleth
- ACM Crowd
- LDAP + GSSAPI/Kerberos and packet signing
- LDAP + TLS encryption (using STARTTLS/STOPTLS commands)

### PR DESCRIPTION
**Pull request by kevinwang**
Temporary fix until auth is moved onto Crowd.

### CODE REVIEW

**Comment by CJS7070** [comment]
AD.UIUC.EDU is being shut down very soon, I'm very reluctant to use it...

**Comment by kevinwang** [comment]
It's better than nothing, if you ask me.

**Comment by colegleason** [comment]
Closing in favor of #287

**Comment by colegleason** [comment]
#287 causes issues. Trying this for a temp fix.

**Comment by colegleason** [comment]
@kevinwang did you verify this works at all? I can't find the LDAP server

**Comment by kevinwang** [comment]
Verified locally. I think you have to be on the campus network or VPN.

**Comment by colegleason** [comment]
I have it working locally but I can't make it work from snake. Trying crowd auth again.

**Pull request merged**
