### PR TITLE
Add a "vend" button to the Caffeine Manager

### PR DESCRIPTION
**Pull request by ace-n**
Allows people to vend sodas from Liquid, since the card reader is broken.

In the future, we should also add either a mobile app and/or Slackbot integration - but maybe that's something for once Groot's done.

@rohankapoorcom Unless I can modify the DB myself, you'll need to run the following command on the DB once this is pushed (to add the **last_vend** column to the **vending** table):

`alter table vending add column last_vend datetime; update vending set last_vend = CURDATE();`

@sskhandek @rohankapoorcom Mind looking over this, and signing off if it looks good?

### CODE REVIEW

**Comment by rohankapoorcom** [comment]
@ace-n Shouldn't you be able to run that alteration as a Django migration? Or does Django not have models for the vending table?

**Comment by ace-n** [comment]
@rohankapoorcom Yeah, come to think of it that's probably the better way to do it.

Let me see if I can get that set up on my end, and I can add it to this PR.

**Comment by rohankapoorcom** [comment]
Yeah, Everything else looks good to me @ace-n but I don't want to sign off on this without that migration.

Thanks.

**Comment by ace-n** [comment]
Migration has been added.

**Comment by rohankapoorcom** [comment]
It's got my sign off. Feel free to deploy it once @sskhandek takes a look.

**Comment by modi95** [comment]
Need a global resource lock on vending. We wouldn't want to find ourselves in a situation where multiple people vend at the same time.

**Comment by sskhandek** [comment]
LGTM

**Comment by ace-n** [comment]
@rohankapoorcom @sskhandek If one of you guys can sign off on this, I'll merge it. @modi95 feel free to take a look too and let me know if I missed anything.

**Comment by sskhandek** [comment]
Looks good!

**Pull request merged**
